export const SET_QUERY = 'SET_QUERY';
export const REQUEST_ARTIST = 'REQUEST_ARTIST';
export const RECEIVE_ARTIST = 'RECEIVE_ARTIST';
export const SET_RECORDS = 'SET_RECORDS';
export const REQUEST_DETAILS = 'REQUEST_DETAILS';
export const RECEIVE_DETAILS = 'RECEIVE_DETAILS';
export const SET_DETAILS = 'SET_DETAILS';
